# Generated by Django 6.0.7 on 2026-07-28 07:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kesiswaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kesiswaan',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=100, unique=True)),
                ('tingkat', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('aktif', 'aktif'), ('alumni', 'alumni')], default='aktif', max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=100)),
                ('jurusan', models.CharField(choices=[('RPL', 'RPL'), ('TKJ', 'TKJ'), ('MPLB', 'MPLB'), ('PM', 'PM'), ('AKL', 'AKL')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('foto_profil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_profil')),
                ('qr_code', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code')),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Tahun_ajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('aktif', 'aktif'), ('nonaktif', 'nonaktif')], default='aktif', max_length=100)),
            ],
            options={
                'db_table': 'tahun_ajaran',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('siswa', 'siswa'), ('kesiswaan', 'kesiswaan')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prestasi', models.CharField(max_length=100)),
                ('tanggal_prestasi', models.DateField()),
                ('penyelenggara', models.CharField(max_length=100)),
                ('tingkat_prestasi', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('diterima', 'diterima'), ('ditolak', 'ditolak')], default='pending', max_length=100)),
                ('kategori_prestasi', models.CharField(choices=[('akademik', 'akademik'), ('non-akademik', 'non-akademik'), ('kejuaraan', 'kejuaraan')], max_length=100)),
                ('kesiswaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprestasi.kesiswaan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprestasi.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprestasi.tahun_ajaran')),
            ],
            options={
                'db_table': 'prestasi',
            },
        ),
        migrations.CreateModel(
            name='Dokumentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('prestasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprestasi.prestasi')),
            ],
            options={
                'db_table': 'dokumentasi',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('deskripsi', models.TextField()),
                ('prestasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprestasi.prestasi')),
            ],
            options={
                'db_table': 'sertifikat',
            },
        ),
        migrations.AddField(
            model_name='siswa',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprestasi.users'),
        ),
        migrations.AddField(
            model_name='kesiswaan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kesiswaan', to='eprestasi.users'),
        ),
    ]
