# Generated by Django 6.0.7 on 2026-08-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='users',
            new_name='Users',
        ),
    ]
