# Generated by Django 6.0.7 on 2026-08-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0002_admin_crud_adjustments'),
        ('eprestasi', '0004_users_created_at_users_updated_at'),
    ]

    operations = [
    ]
