# Generated by Django 6.0.7 on 2026-08-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0004_prestasi_alasan_penolakan'),
        ('eprestasi', '0006_merge_0003_role_super_admin_0005_merge_20260809_1909'),
    ]

    operations = [
    ]
