# Generated by Django 6.0.7 on 2026-08-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0005_prestasi_tanggal_upload_verifikasi'),
        ('eprestasi', '0007_merge_20260820_0810'),
    ]

    operations = [
    ]
