# Generated by Django 6.1 on 2026-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0009_alter_siswa_jurusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(blank=True, choices=[('X PPLG 1', 'X PPLG 1'), ('X PPLG 2', 'X PPLG 2'), ('X DKV 1', 'X DKV 1'), ('X DKV 2', 'X DKV 2'), ('X TJKT 1', 'X TJKT 1'), ('X PM 1', 'X PM 1'), ('X PM 2', 'X PM 2'), ('X PM 3', 'X PM 3'), ('X MP 1', 'X MP 1'), ('X MP 2', 'X MP 2'), ('X MP 3', 'X MP 3'), ('X MP 4', 'X MP 4'), ('X MP 5', 'X MP 5'), ('X AKL 1', 'X AKL 1'), ('X AKL 2', 'X AKL 2'), ('X AKL 3', 'X AKL 3'), ('X AKL 4', 'X AKL 4'), ('XI RPL 1', 'XI RPL 1'), ('XI RPL 2', 'XI RPL 2'), ('XI DKV 1', 'XI DKV 1'), ('XI DKV 2', 'XI DKV 2'), ('XI TJKT 1', 'XI TJKT 1'), ('XI PM 1', 'XI PM 1'), ('XI PM 2', 'XI PM 2'), ('XI PM 3', 'XI PM 3'), ('XI MP 1', 'XI MP 1'), ('XI MP 2', 'XI MP 2'), ('XI MP 3', 'XI MP 3'), ('XI MP 4', 'XI MP 4'), ('XI MP 5', 'XI MP 5'), ('XI AKL 1', 'XI AKL 1'), ('XI AKL 2', 'XI AKL 2'), ('XI AKL 3', 'XI AKL 3'), ('XI AKL 4', 'XI AKL 4'), ('XII RPL 1', 'XII RPL 1'), ('XII RPL 2', 'XII RPL 2'), ('XII DKV 1', 'XII DKV 1'), ('XII DKV 2', 'XII DKV 2'), ('XII TJKT 1', 'XII TJKT 1'), ('XII PM 1', 'XII PM 1'), ('XII PM 2', 'XII PM 2'), ('XII PM 3', 'XII PM 3'), ('XII MP 1', 'XII MP 1'), ('XII MP 2', 'XII MP 2'), ('XII MP 3', 'XII MP 3'), ('XII MP 4', 'XII MP 4'), ('XII MP 5', 'XII MP 5'), ('XII AKL 1', 'XII AKL 1'), ('XII AKL 2', 'XII AKL 2'), ('XII AKL 3', 'XII AKL 3'), ('XII AKL 4', 'XII AKL 4')], max_length=100, null=True),
        ),
    ]
