# Generated by Django 6.1 on 2026-09-06 21:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0010_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='dokumen_puspresnas',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='dokumen_puspresnas'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='jenis_penyelenggara_puspresnas',
            field=models.CharField(blank=True, choices=[('kementerian', 'Kementerian'), ('non_kementerian', 'Non-Kementerian (Swasta)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='jenis_wilayah_puspresnas',
            field=models.CharField(blank=True, choices=[('dalam_negeri', 'Dalam Negeri'), ('luar_negeri', 'Luar Negeri')], max_length=50, null=True),
        ),
    ]
