# Generated by Django 6.0.7 on 2026-08-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0002_rename_users_siswa_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='Users',
            new_name='users',
        ),
    ]
