# Generated by Django 6.0.7 on 2026-08-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0003_role_super_admin'),
        ('eprestasi', '0005_merge_20260809_1909'),
    ]

    operations = [
    ]
