# Generated by Django 6.0.7 on 2026-09-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0008_merge_20260827_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='jurusan',
            field=models.CharField(blank=True, choices=[('RPL', 'RPL'), ('DKV', 'DKV'), ('TJKT', 'TJKT'), ('AKL', 'AKL'), ('MPLB', 'MPLB'), ('PM', 'PM')], max_length=100, null=True),
        ),
    ]
