# Generated by Django 6.0.7 on 2026-09-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0010_prestasi_dokumen_puspresnas_and_more'),
        ('eprestasi', '0011_prestasi_dokumen_puspresnas_and_more'),
    ]

    operations = [
    ]
