# Generated by Django 6.0.7 on 2026-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0013_logaktivitas_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='catatan_perbaikan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='jenis_perbaikan',
            field=models.CharField(blank=True, choices=[('data', 'Perbaikan Data'), ('file', 'Perbaikan File')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('diterima', 'diterima'), ('perbaikan', 'perbaikan'), ('ditolak', 'ditolak')], default='pending', max_length=100),
        ),
    ]
