# Generated by Django 6.0.7 on 2026-09-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0014_prestasi_catatan_perbaikan_prestasi_jenis_perbaikan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='kategori_prestasi',
            field=models.CharField(choices=[('akademik', 'akademik'), ('non-akademik', 'non-akademik')], max_length=100),
        ),
    ]
