# Generated by Django 6.0.7 on 2026-09-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0016_users_auth_key_status_akun'),
        ('eprestasi', '0016_users_auth_key_users_status_akun'),
    ]

    operations = [
    ]
