# Generated by Django 6.0.7 on 2026-09-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0017_merge_20260926_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='auth_key',
        ),
        migrations.RemoveField(
            model_name='users',
            name='status_akun',
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='kategori_prestasi',
            field=models.CharField(choices=[('akademik', 'akademik'), ('non-akademik', 'non-akademik'), ('kejuaraan', 'kejuaraan')], max_length=100),
        ),
    ]
