# Generated by Django 6.0.7 on 2026-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0018_remove_users_auth_key_remove_users_status_akun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='kode_puspresnas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
