# Generated by Django 6.0.7 on 2026-09-27 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0019_prestasi_kode_puspresnas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='jurusan',
            field=models.CharField(blank=True, choices=[('RPL', 'RPL'), ('DKV', 'DKV'), ('TKJ', 'TKJ'), ('AKL', 'AKL'), ('MPLB', 'MPLB'), ('PM', 'PM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(blank=True, choices=[('X PPLG 1', 'X PPLG 1'), ('X PPLG 2', 'X PPLG 2'), ('X DKV 1', 'X DKV 1'), ('X DKV 2', 'X DKV 2'), ('X TKJ 1', 'X TKJ 1'), ('X PM 1', 'X PM 1'), ('X PM 2', 'X PM 2'), ('X PM 3', 'X PM 3'), ('X MP 1', 'X MP 1'), ('X MP 2', 'X MP 2'), ('X MP 3', 'X MP 3'), ('X MP 4', 'X MP 4'), ('X MP 5', 'X MP 5'), ('X AKL 1', 'X AKL 1'), ('X AKL 2', 'X AKL 2'), ('X AKL 3', 'X AKL 3'), ('X AKL 4', 'X AKL 4'), ('XI RPL 1', 'XI RPL 1'), ('XI RPL 2', 'XI RPL 2'), ('XI DKV 1', 'XI DKV 1'), ('XI DKV 2', 'XI DKV 2'), ('XI TKJ 1', 'XI TKJ 1'), ('XI PM 1', 'XI PM 1'), ('XI PM 2', 'XI PM 2'), ('XI PM 3', 'XI PM 3'), ('XI MP 1', 'XI MP 1'), ('XI MP 2', 'XI MP 2'), ('XI MP 3', 'XI MP 3'), ('XI MP 4', 'XI MP 4'), ('XI MP 5', 'XI MP 5'), ('XI AKL 1', 'XI AKL 1'), ('XI AKL 2', 'XI AKL 2'), ('XI AKL 3', 'XI AKL 3'), ('XI AKL 4', 'XI AKL 4'), ('XII RPL 1', 'XII RPL 1'), ('XII RPL 2', 'XII RPL 2'), ('XII DKV 1', 'XII DKV 1'), ('XII DKV 2', 'XII DKV 2'), ('XII TKJ 1', 'XII TKJ 1'), ('XII PM 1', 'XII PM 1'), ('XII PM 2', 'XII PM 2'), ('XII PM 3', 'XII PM 3'), ('XII MP 1', 'XII MP 1'), ('XII MP 2', 'XII MP 2'), ('XII MP 3', 'XII MP 3'), ('XII MP 4', 'XII MP 4'), ('XII MP 5', 'XII MP 5'), ('XII AKL 1', 'XII AKL 1'), ('XII AKL 2', 'XII AKL 2'), ('XII AKL 3', 'XII AKL 3'), ('XII AKL 4', 'XII AKL 4')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
                ('jurusan', models.CharField(choices=[('RPL', 'RPL'), ('TKJ', 'TKJ'), ('DKV', 'DKV'), ('MPLB', 'MPLB'), ('AKL', 'AKL'), ('PM', 'PM')], max_length=10)),
                ('tingkat', models.PositiveSmallIntegerField(choices=[(10, 'X'), (11, 'XI'), (12, 'XII')])),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_kelas', to='eprestasi.tahun_ajaran')),
            ],
            options={
                'db_table': 'kelas',
                'ordering': ['tahun_ajaran_id', 'jurusan', 'tingkat', 'nama_kelas'],
                'unique_together': {('nama_kelas', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='LogPerubahanKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_perubahan', models.CharField(choices=[('penempatan_awal', 'Penempatan awal'), ('pembagian_ulang_x_ke_xi', 'Pembagian ulang kelas X ke XI'), ('kenaikan_otomatis_xi_ke_xii', 'Kenaikan otomatis XI ke XII'), ('perubahan_manual', 'Perubahan manual')], max_length=30)),
                ('alasan_perubahan', models.TextField(blank=True, null=True)),
                ('waktu_perubahan', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eprestasi.users')),
                ('kelas_baru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eprestasi.kelas')),
                ('kelas_sebelumnya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eprestasi.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_perubahan_kelas', to='eprestasi.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_perubahan_kelas', to='eprestasi.tahun_ajaran')),
            ],
            options={
                'db_table': 'log_perubahan_kelas',
                'ordering': ['-waktu_perubahan'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.PositiveSmallIntegerField(choices=[(10, 'X'), (11, 'XI'), (12, 'XII')])),
                ('tanggal_penempatan', models.DateTimeField(default=django.utils.timezone.now)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eprestasi.users')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas', to='eprestasi.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas', to='eprestasi.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas', to='eprestasi.tahun_ajaran')),
            ],
            options={
                'db_table': 'riwayat_kelas',
                'ordering': ['tahun_ajaran_id', 'siswa_id'],
                'unique_together': {('siswa', 'tahun_ajaran')},
            },
        ),
    ]
