# Generated by Django 6.0.7 on 2026-09-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0020_alter_siswa_jurusan_alter_siswa_kelas_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesiswaan',
            name='status',
            field=models.CharField(choices=[('aktif', 'aktif'), ('nonaktif', 'nonaktif')], default='aktif', max_length=20),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='modul',
            field=models.CharField(blank=True, choices=[('siswa', 'Siswa'), ('kesiswaan', 'Kesiswaan'), ('admin', 'Admin'), ('tahun_ajaran', 'Tahun Ajaran'), ('kelas', 'Kelas'), ('prestasi', 'Prestasi'), ('kelulusan', 'Kelulusan'), ('import', 'Import')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='role_actor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='status_log',
            field=models.CharField(choices=[('berhasil', 'Berhasil'), ('gagal', 'Gagal')], default='berhasil', max_length=20),
        ),
        migrations.AddField(
            model_name='siswa',
            name='status_kelulusan',
            field=models.CharField(choices=[('belum_diproses', 'Belum Diproses'), ('lulus', 'Lulus'), ('tidak_lulus', 'Tidak Lulus')], default='belum_diproses', max_length=20),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tanggal_kelulusan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='aksi',
            field=models.CharField(choices=[('akun_dibuat', 'Akun dibuat'), ('akun_diubah', 'Akun diubah'), ('akun_dihapus', 'Akun dihapus'), ('status_diubah', 'Status diubah'), ('user_diimport', 'User diimport'), ('tahun_ajaran_ditambah', 'Tahun ajaran ditambah'), ('tahun_ajaran_diubah', 'Tahun ajaran diubah'), ('prestasi_diverifikasi', 'Prestasi diverifikasi'), ('kelas_dibuat', 'Kelas dibuat'), ('kelas_dihapus', 'Kelas dihapus'), ('siswa_ditempatkan_kelas', 'Siswa ditempatkan ke kelas'), ('kelulusan_diproses', 'Kelulusan diproses'), ('password_direset', 'Password direset')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('aktif', 'aktif'), ('nonaktif', 'nonaktif'), ('alumni', 'alumni')], default='aktif', max_length=100),
        ),
    ]
