# Generated by Django 6.0.7 on 2026-09-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0021_kesiswaan_status_logaktivitas_modul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesiswaan',
            name='no_hp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kesiswaan',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('Wakil Kesiswaan', 'Wakil Kesiswaan'), ('Ketua Kesiswaan', 'Ketua Kesiswaan')], max_length=100, null=True),
        ),
    ]
