# Generated by Django 6.0.7 on 2026-09-29 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0022_kesiswaan_no_hp_alter_kesiswaan_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifikasiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('pesan', models.CharField(max_length=255)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibaca', models.BooleanField(default=False)),
                ('prestasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_siswa', to='eprestasi.prestasi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='eprestasi.siswa')),
            ],
            options={
                'db_table': 'notifikasi_siswa',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='NotifikasiDibaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibaca_pada', models.DateTimeField(default=django.utils.timezone.now)),
                ('kesiswaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_dibaca', to='eprestasi.kesiswaan')),
                ('prestasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_dibaca', to='eprestasi.prestasi')),
            ],
            options={
                'db_table': 'notifikasi_dibaca',
                'unique_together': {('kesiswaan', 'prestasi')},
            },
        ),
    ]
