# Generated by Django 6.0.7 on 2026-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0023_notifikasisiswa_notifikasidibaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
