# Generated by Django 6.0.7 on 2026-10-05 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprestasi', '0025_prestasi_wilayah_prestasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunci', models.CharField(max_length=64, unique=True)),
                ('jumlah_gagal', models.PositiveIntegerField(default=0)),
                ('terakhir_gagal', models.DateTimeField(default=django.utils.timezone.now)),
                ('terkunci_sampai', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_attempt',
            },
        ),
    ]
